/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAuditRouteImport } from './routes/dashboard.audit'
import { Route as DashboardDatasetsRouteImport } from './routes/dashboard.datasets'
import { Route as DashboardFederatedRouteImport } from './routes/dashboard.federated'
import { Route as DashboardInsightsRouteImport } from './routes/dashboard.insights'
import { Route as DashboardInstitutionsRouteImport } from './routes/dashboard.institutions'
import { Route as DashboardRequestsRouteImport } from './routes/dashboard.requests'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDatasetsRoute = DashboardDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFederatedRoute = DashboardFederatedRouteImport.update({
  id: '/federated',
  path: '/federated',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInsightsRoute = DashboardInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInstitutionsRoute = DashboardInstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRequestsRoute = DashboardRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/datasets': typeof DashboardDatasetsRoute
  '/dashboard/federated': typeof DashboardFederatedRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/institutions': typeof DashboardInstitutionsRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/datasets': typeof DashboardDatasetsRoute
  '/dashboard/federated': typeof DashboardFederatedRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/institutions': typeof DashboardInstitutionsRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/datasets': typeof DashboardDatasetsRoute
  '/dashboard/federated': typeof DashboardFederatedRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/institutions': typeof DashboardInstitutionsRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/audit'
    | '/dashboard/datasets'
    | '/dashboard/federated'
    | '/dashboard/insights'
    | '/dashboard/institutions'
    | '/dashboard/requests'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/audit'
    | '/dashboard/datasets'
    | '/dashboard/federated'
    | '/dashboard/insights'
    | '/dashboard/institutions'
    | '/dashboard/requests'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/audit'
    | '/dashboard/datasets'
    | '/dashboard/federated'
    | '/dashboard/insights'
    | '/dashboard/institutions'
    | '/dashboard/requests'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/datasets': {
      id: '/dashboard/datasets'
      path: '/datasets'
      fullPath: '/dashboard/datasets'
      preLoaderRoute: typeof DashboardDatasetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/federated': {
      id: '/dashboard/federated'
      path: '/federated'
      fullPath: '/dashboard/federated'
      preLoaderRoute: typeof DashboardFederatedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/insights': {
      id: '/dashboard/insights'
      path: '/insights'
      fullPath: '/dashboard/insights'
      preLoaderRoute: typeof DashboardInsightsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/institutions': {
      id: '/dashboard/institutions'
      path: '/institutions'
      fullPath: '/dashboard/institutions'
      preLoaderRoute: typeof DashboardInstitutionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/requests': {
      id: '/dashboard/requests'
      path: '/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof DashboardRequestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardDatasetsRoute: typeof DashboardDatasetsRoute
  DashboardFederatedRoute: typeof DashboardFederatedRoute
  DashboardInsightsRoute: typeof DashboardInsightsRoute
  DashboardInstitutionsRoute: typeof DashboardInstitutionsRoute
  DashboardRequestsRoute: typeof DashboardRequestsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardDatasetsRoute: DashboardDatasetsRoute,
  DashboardFederatedRoute: DashboardFederatedRoute,
  DashboardInsightsRoute: DashboardInsightsRoute,
  DashboardInstitutionsRoute: DashboardInstitutionsRoute,
  DashboardRequestsRoute: DashboardRequestsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
